### ISSUE TITLE
Doc : Ajout d'une nouvelle page dans la grille d'audit

### ISSUE THREAD

**Issue by lbuffet-pro** [copsae/outils-audits-accessibilite#12]
Pour ajouter une feuille dans la grille d'audit :
- Insérer une nouvelle ligne dans l'onglet "échantillon" et renseigner dans chaque case correspondante le numéro de page, le titre de la page, l'url et un commentaire si nécessaire ;
- Dupliquer l'onglet correspondant à la dernière page en prenant soin de le renommer avec le numéro de page et de le placer à la suite du dernier onglet actuel ;
- Dans l'onglet "calculs", insérer une nouvelle ligne juste avant la ligne "Totaux pour les pages".
- Sélectionner la case "Page" de la ligne située au dessus de la ligne nouvellement ajoutée. Cliquer sur la touche "Maj" et, en maintenant la touche appuyée, cliquer sur le coin en bas à droite de la case pour l'étendre sur la case située en dessous. Cette technique permet de récupérer la formule de la case précédente en incrémentant de 1. 
- Procéder de même pour les cases "Nombre de règles avec au moins un problème détecté" et "Nombre de règles restant à évaluer". Attention : pour ces cases l'incrémentation ne s'effectue pas de manière correcte, il faut modifier la formule avec le nom de page correspondant et la plage d'échantillon à évaluer.
- Dans l'onglet de la nouvelle page, modifier la ligne 2 en copiant-collant la formule de l'onglet précédent et en incrémentant.

**Comment by juliemoynatPro** [comment]
Je propose ceci.

Dans la partie « Comment fonctionne cet outil ? », modifier la ligne :

>10 pages : La grille a été prévue pour 10 pages mais vous pouvez en ajouter autant que vous voulez ou en supprimer. Pour cela, il faudra modifier les onglets « Échantillon » et « Calculs ». Il faudra également soit supprimer les onglets « PXX » en trop ou en ajouter en dupliquant le dernier. Nous conseillons d’utiliser la page 1 pour analyser les éléments transverses à toutes les pages (en-tête, pied de page, etc.) afin d’éviter de les analyser dans chaque page.

par :

>10 pages : La grille a été prévue pour 10 pages mais vous pouvez en ajouter autant que vous voulez ou en supprimer. Pour cela, voir la partie « Comment augmenter le nombre de pages dans la grille ? ». Nous conseillons d’utiliser la page 1 pour analyser les éléments transverses à toutes les pages (en-tête, pied de page, etc.) afin d’éviter de les analyser dans chaque page.

Puis, ajouter une partie « Comment augmenter le nombre de pages dans la grille ? » qui dirait ceci (pour l'audit flash donc à adapter pour l'audit flash graphisme) :

>1. **Insérer une nouvelle ligne dans le tableau de l’onglet « Échantillon »** et renseigner, dans chaque case correspondante, le numéro de page, le titre de la page, l’URL et un commentaire si nécessaire ;
>1. **Dupliquer le dernier onglet :** cliquer droit sur l’onglet correspondant à la dernière page. Aller dans le menu « Déplacer/copier la feuille ». Dans la fenêtre qui s’ouvre, sélectionner « Copier » comme action. Dans la partie « Insérer avant », sélectionner « - placer en dernière position - ». Indiquer « P11 » comme « Nouveau nom » (ou autre numéro correspondant).
>1. En principe, l’onglet s’affiche à peu près correctement. Cependant, **certaines formules ne sont pas bonnes**. Si vous cliquez sur la cellule B7, vous devriez voir une formule correspondant à « P01.B7 ». Faites CTRL+H pour lancer un Rechercher-Remplacer. Rechercher « P01 » et le remplacer par « 'Règles (modèle)' » (apostrophes incluses) partout (bouton « Tout remplacer »).
>1. **Autre formule cassée en A2:G2 :** normalement, vous avez « CONCATENER(Calculs.A18;" - ";Calculs.B18;" : ";Calculs.C18) » qui pointe donc vers le mauvais onglet « Calculs ». Il faut la remplacer par « CONCATENER(Échantillon.A19;" - ";Échantillon.B19;" : ";Échantillon.C19) » pour que ça pointe sur le bon onglet et la bonne ligne (les cellules A19, B19, C19 sont à adapter selon la page).
>1. **Dans l’onglet « Calculs », insérer une nouvelle ligne juste avant la ligne « Totaux pour toutes les pages ».** Sélectionner les cellules du tableau de la ligne au-dessus de la ligne nouvellement ajoutée. Appuyer sur la touche « Maj » du clavier et, en maintenant la touche appuyée, cliquer à la souris sur le coin en bas à droite de la cellule pour l’étendre sur les cellules situées en dessous. Cette technique permet de récupérer les formules des cellules précédentes en incrémentant de 1.
>1. **Formules cassés pour les cellules des colonnes « Nombre de règles avec au moins un problème détecté (oui) » et « Nombre de règles restant à évaluer (NT) » :** pour ces cellules l’incrémentation ne s’effectue pas de manière correcte. Il faut modifier la formule avec le nom de page correspondant (P11 au lieu de P10) et la plage d’échantillon à évaluer (en colonne B : F4 et F47 au lieu de F5 et F48 puis, en colonne C : F4 et F37 au lieu de F5 et F38).

**Comment by lbuffet-pro** [comment]
Testé et approuvé de mon côté 👍

**Comment by juliemoynatPro** [comment]
Boooon finalement, mauvaise utilisation des formules de ma part. Quand on utilise la référence à un onglet avec le signe $, il y a plein de choses qui fonctionnent mieux.

Donc je modifie la doc comme suit :

>1. **Insérer une nouvelle ligne dans le tableau de l’onglet « Échantillon »** et renseigner, dans chaque case correspondante, le numéro de page, le titre de la page, l’URL et un commentaire si nécessaire ;
>1. **Dupliquer le dernier onglet :** cliquer droit sur l’onglet correspondant à la dernière page. Aller dans le menu « Déplacer/copier la feuille ». Dans la fenêtre qui s’ouvre, sélectionner « Copier » comme action. Dans la partie « Insérer avant », sélectionner « - placer en dernière position - ». Indiquer « P11 » comme « Nouveau nom » (ou autre numéro correspondant).
>1. En principe, l’onglet s’affiche à peu près correctement. Cependant, il faut **corriger la formule en A2:G2**. Normalement, vous avez « =CONCATENER($Échantillon.A18;" - ";$Échantillon.B18;" : ";$Échantillon.C18) » qui pointe vers la ligne pour la page 10 dans l'onglet appelé « Échantillon ». Remplacer A18, B18 et C18 par A19, B19 et C19 (à adapter selon la page, bien sûr).
>1. **Dans l’onglet « Calculs », insérer une nouvelle ligne juste avant la ligne « Totaux pour toutes les pages ».** Sélectionner les cellules du tableau de la ligne au-dessus de la ligne nouvellement ajoutée. Appuyer sur la touche « Maj » du clavier et, en maintenant la touche appuyée, cliquer à la souris sur le coin en bas à droite de la cellule pour l’étendre sur les cellules situées en dessous. Cette technique permet de récupérer les formules des cellules précédentes en incrémentant de 1.
>1. **Formules cassés pour les cellules des colonnes « Nombre de règles avec au moins un problème détecté (oui) » et « Nombre de règles restant à évaluer (NT) » :** pour ces cellules l’incrémentation ne s’effectue pas de manière correcte. Il faut modifier la formule avec le nom de page correspondant (P11 au lieu de P10) et la plage d’échantillon à évaluer (en colonne B : F4 et F47 au lieu de F5 et F48 puis, en colonne C : F4 et F37 au lieu de F5 et F38).

Je te dis quand la PR est prête à vérifier pour que tu testes en fonction de la doc.
