### ISSUE TITLE
Erreur avec la moulinette

### ISSUE THREAD

**Issue by bckthomas** [copsae/outils-audits-accessibilite#33]
Bonjour
J'ai essayé la moulinette avec un fichier mais je rencontre cette erreur : 
Fatal error: Uncaught Error: Call to a member function getValue() on null in /home/clients/0d441c86fa9a3b8527c210a883a4b86d/sites/moulinette/src/AuditDataAnalyser.php:82 Stack trace: #0 /home/clients/0d441c86fa9a3b8527c210a883a4b86d/sites/moulinette/src/AuditDataAnalyser.php(18): Copsae\AuditDataAnalyser->collectAnomalyList() #1 /home/clients/0d441c86fa9a3b8527c210a883a4b86d/sites/moulinette/index.php(22): Copsae\AuditDataAnalyser->processAnomalyList() #2 {main} thrown in /home/clients/0d441c86fa9a3b8527c210a883a4b86d/sites/moulinette/src/AuditDataAnalyser.php on line 82

Je peux envoyer le fichier si besoin
Merci

**Comment by juliemoynatPro** [comment]
Bonjour,

Je veux bien ton fichier pour comprendre, effectivement. Peux-tu l'envoyer sur bonjour@copsae.fr ? On garde ça privé le temps de comprendre d'où vient le problème, bien entendu.

**Comment by juliemoynatPro** [comment]
Bonjour @bckthomas,

Après analyse, @mloyat a trouvé la réponse et la solution https://github.com/copsae/outils-audits-accessibilite/pull/34/files (Merci !)

Le correctif vient d'être mis en ligne !

Merci de nous avoir remonté ce problème.
